### ISSUE TITLE
Provide a plugin to replace Git information placeholders with actual values.

### ISSUE THREAD

**Issue by kherge** [Sqon/app#2]
## Problem

I have noticed that many projects (including my own)<sup>1, 2</sup> rely on Git's commit hash and tag names to embed the version of a project. It would be very useful to have a plugin that will replace arbitrary patterns with their corresponding values from Git.
## Resolution

I would like to use the following build configuration to get Git information:

``` yaml
# The Git plugin settings.
git:

    # Replace "@git-commit@" with the commit hash.
    commit: '/@git-commit@/'

    # Replace "@git-commit-short@" with the short version of the commit hash.
    commit-short: '/@git-commit-short@/'

    # Replace "@git-tag@" with the current tag name.
    tag: '/@git-tag@/'

# The Sqon build configuration settings.
sqon:

    # Load the Git and Replace plugins.
    plugins:
        - class: Sqon\Builder\Plugin\Git
        - class: Sqon\Builder\Plugin\Replace
```
## References
1. https://github.com/box-project/box2/blob/2.0/src/lib/KevinGH/Box/Application.php#L25
2. https://github.com/composer/composer/blob/master/src/Composer/Composer.php#L31-L33

**Comment by kherge** [comment]
Commit cf526cc added this feature, but you have to use it with the Replace plugin.

``` yaml
git:
    commit: '/\$commit\$/'
    commit-date: '/\$commit-date\$/'
    commit-short: '/\$commit-short\$/'
    commit-tag: '/\$commit-tag\$/'
    tag: '/\$tag\$/'

replace:
    all:
        '/\$tag\$/': 'Tag: %s'

    path:
        'src/build.php':
            '/\$commit\$/': 'Commit: %s'
            '/\$commit-date\$/': 'Date: %s'
            '/\$commit-tag\$/': 'Exact Tag: %s'

    pattern:
        '/\.php$/':
            '/\$commit-short\$/': '%s'

sqon:
    plugins:
        - class: Sqon\Builder\Plugin\Git
        - class: Sqon\Builder\Plugin\Replace
```
