### ISSUE TITLE
Provide a plugin for date and time replacements.

### ISSUE THREAD

**Issue by kherge** [Sqon/app#3]
## Problem

Some projects<sup>1</sup> need to replace a specific pattern with a current or relative date and time<sup>2</sup>. It would be very useful to have a plugin that can replace the patterns with their corresponding values.
## Resolution

I would like to be able to use the following build configuration settings:

``` yaml
# The date and time plugin settings.
date:

    # Replace "@now@" with the current date and time.
    - format: 'Y-m-d H:i:s'
      pattern: '/@now@/'

    # Replace "@tomorrow@" with a future date and time.
    - format: 'F j, Y at H:i A'
      pattern: '/@tomorrow@/'
      time: 'tomorrow'
```
## References
1. https://github.com/composer/composer/blob/master/src/Composer/Compiler.php#L257-L261
2. https://secure.php.net/manual/en/function.strtotime.php

**Comment by kherge** [comment]
Commit f529c4d adds this feature.

The configuration settings for `Date` also support timezones.

``` yaml
date:

    - pattern: '/default/'
      # default values:
      # format: 'c'
      # when: 'now'
      # zone: 'UTC'

    - pattern: '/tomorrow/'
      format: 'r'
      when: 'tomorrow'
      zone: 'America/Los_Angeles'
```
